-- 코드를 입력하세요
SET @COUNT = -1;
SELECT A.NAME, A.DATETIME
FROM ANIMAL_INS A LEFT OUTER JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.ANIMAL_ID is null and (@COUNT := @COUNT + 1) < 3
ORDER BY A.DATETIME