-- 리뷰가 가장 많이 작성된 회원의 리뷰를 조회
-- 리뷰 작성일 기준 오름차순, 리뷰 텍스트 기준으로 오름차순
SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d')
FROM MEMBER_PROFILE M INNER JOIN REST_REVIEW R
ON M.MEMBER_ID = R.MEMBER_ID
where M.MEMBER_ID = (SELECT MEMBER_ID FROM REST_REVIEW 
                    GROUP BY MEMBER_ID
                    ORDER BY COUNT(*) DESC LIMIT 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT;